"""E-commerce platform presets.

Each platform defines the recommended *set* of listing images (ordered by the
conversion-optimised sequence recommended by top sellers), the export size, the
square aspect ratio to use for the main images, the default on-image text
language, and a text density preference. Selecting a platform in the UI
auto-applies its recommended set, language and density.

textDensity controls how much on-image text the platform wants overall and
modulates each template's own textLevel:
- "clean"    - western marketplaces (Amazon/eBay/Walmart...) that favour clean,
  minimal-text imagery; even info templates stay restrained.
- "balanced" - a moderate amount of text.
- "rich"     - Chinese-style marketplaces (淘宝/天猫/京东/拼多多) that favour
  information-dense, text-heavy 卖点长图.
"""

from typing import Any, Dict, List

PLATFORMS: List[Dict[str, Any]] = [
    # ============================ 北美 ============================ #
    {
        "id": "amazon",
        "name": "Amazon",
        "region": "北美 · 全球",
        "language": "en",
        "size": "2000×2000",
        "aspect": "1024x1024",
        # White background main image, no text; then infographic, lifestyle...
        "textDensity": "clean",
        "templates": [
            "white_background",
            "feature_infographic",
            "lifestyle_scene",
            "dimension_infographic",
            "in_use_scene",
            "comparison",
            "packaging",
        ],
        "note": "主图必须纯白底(RGB 255)且无文字/logo，产品占比≥85%，长边≥1600px(建议2000px可缩放)；整体偏干净少字。",
    },
    {
        "id": "walmart",
        "name": "Walmart",
        "region": "北美",
        "language": "en",
        "size": "2200×2200",
        "aspect": "1024x1024",
        "textDensity": "clean",
        "templates": [
            "white_background",
            "feature_infographic",
            "lifestyle_scene",
            "dimension_infographic",
            "detail_closeup",
        ],
        "note": "主图纯白底无文字，建议 2200px、长边≥1000px；整体偏干净少字。",
    },
    {
        "id": "target",
        "name": "Target",
        "region": "北美",
        "language": "en",
        "size": "1200×1200",
        "aspect": "1024x1024",
        "textDensity": "clean",
        "templates": [
            "white_background",
            "lifestyle_scene",
            "feature_infographic",
            "detail_closeup",
            "in_use_scene",
        ],
        "note": "主图纯白底、产品占比≥85%，建议 1200px 起；辅图偏生活化，少字。",
    },
    {
        "id": "bestbuy",
        "name": "Best Buy",
        "region": "北美",
        "language": "en",
        "size": "1500×1500",
        "aspect": "1024x1024",
        "textDensity": "balanced",
        "templates": [
            "white_background",
            "multi_angle",
            "param_table",
            "feature_infographic",
            "dimension_infographic",
            "detail_closeup",
        ],
        "note": "3C 数码为主，主图白底，重视规格参数图与多角度；均衡文字。",
    },
    {
        "id": "ebay",
        "name": "eBay",
        "region": "北美 · 全球",
        "language": "en",
        "size": "1600×1600",
        "aspect": "1024x1024",
        "textDensity": "clean",
        "templates": [
            "white_background",
            "multi_angle",
            "detail_closeup",
            "lifestyle_scene",
            "feature_infographic",
        ],
        "note": "首图白底无边框、最长边建议≥1600px；整体偏干净少字。",
    },
    # ============================ 中国 ============================ #
    {
        "id": "taobao",
        "name": "淘宝",
        "region": "中国",
        "language": "zh",
        "size": "800 / 1000",
        "aspect": "1024x1024",
        "textDensity": "rich",
        "templates": [
            "benefit_banner",
            "feature_infographic",
            "lifestyle_scene",
            "param_table",
            "guarantee",
            "white_background",
            "detail_closeup",
        ],
        "note": "主图可带文字卖点，第5张需白底无文字，详情页 750 宽；偏富信息长图。",
    },
    {
        "id": "tmall",
        "name": "天猫",
        "region": "中国",
        "language": "zh",
        "size": "800 / 1000",
        "aspect": "1024x1024",
        "textDensity": "rich",
        "templates": [
            "benefit_banner",
            "model_shot",
            "feature_infographic",
            "param_table",
            "certification",
            "lifestyle_scene",
            "white_background",
        ],
        "note": "品牌旗舰，模特图基本必备，第5张白底无文字；偏富信息。",
    },
    {
        "id": "jd",
        "name": "京东",
        "region": "中国",
        "language": "zh",
        "size": "800×800",
        "aspect": "1024x1024",
        "textDensity": "rich",
        "templates": [
            "white_background",
            "benefit_banner",
            "feature_infographic",
            "param_table",
            "guarantee",
            "dimension_infographic",
            "detail_closeup",
        ],
        "note": "主图白底居中，800px 起支持放大镜；偏富信息。",
    },
    {
        "id": "pdd",
        "name": "拼多多",
        "region": "中国",
        "language": "zh",
        "size": "750×750",
        "aspect": "1024x1024",
        "textDensity": "rich",
        "templates": [
            "benefit_banner",
            "white_background",
            "comparison",
            "feature_infographic",
            "guarantee",
            "how_to_use",
        ],
        "note": "主图无白边、卖点大字突出性价比；偏富信息。",
    },
    {
        "id": "douyin",
        "name": "抖音电商",
        "region": "中国",
        "language": "zh",
        "size": "1080×1080 / 3:4",
        "aspect": "1024x1024",
        "textDensity": "rich",
        "templates": [
            "vertical_lifestyle",
            "benefit_banner",
            "model_shot",
            "feature_infographic",
            "how_to_use",
            "white_background",
        ],
        "note": "兴趣电商，竖版/短视频风+大字卖点，模特实拍带货感；偏富信息。",
    },
    {
        "id": "xiaohongshu",
        "name": "小红书",
        "region": "中国",
        "language": "zh",
        "size": "1080×1440 / 3:4",
        "aspect": "1024x1024",
        "textDensity": "balanced",
        "templates": [
            "flat_lay",
            "lifestyle_scene",
            "closeup_model",
            "scene_selling",
            "brand_story",
        ],
        "note": "种草社区，竖版 3:4、精致生活方式/平铺质感，文字克制有格调；均衡。",
    },
    # ======================= 日本 · 韩国 ======================= #
    {
        "id": "rakuten",
        "name": "楽天 Rakuten",
        "region": "日本",
        "language": "ja",
        "size": "1000×1000",
        "aspect": "1024x1024",
        "textDensity": "rich",
        "templates": [
            "white_background",
            "feature_infographic",
            "param_table",
            "benefit_banner",
            "guarantee",
            "how_to_use",
        ],
        "note": "代表画像文字占比需<20%(便于搜索)，其余详情图日式富信息长图、参数齐全；建议≥700px。",
    },
    {
        "id": "amazon_jp",
        "name": "Amazon 日本",
        "region": "日本",
        "language": "ja",
        "size": "2000×2000",
        "aspect": "1024x1024",
        "textDensity": "balanced",
        "templates": [
            "white_background",
            "feature_infographic",
            "param_table",
            "lifestyle_scene",
            "dimension_infographic",
        ],
        "note": "主图纯白底无文字、长边≥1600px；日区辅图信息比欧美更足，均衡偏富。",
    },
    {
        "id": "coupang",
        "name": "쿠팡 Coupang",
        "region": "韩国",
        "language": "ko",
        "size": "1000×1000",
        "aspect": "1024x1024",
        "textDensity": "rich",
        "templates": [
            "white_background",
            "benefit_banner",
            "feature_infographic",
            "param_table",
            "how_to_use",
            "guarantee",
        ],
        "note": "代表图白底无文字、≥1000px；详情页为韩式超长富信息图；偏富信息。",
    },
    {
        "id": "gmarket",
        "name": "G마켓 Gmarket",
        "region": "韩国",
        "language": "ko",
        "size": "1000×1000",
        "aspect": "1024x1024",
        "textDensity": "rich",
        "templates": [
            "benefit_banner",
            "white_background",
            "feature_infographic",
            "model_shot",
            "param_table",
            "guarantee",
        ],
        "note": "韩式促销风，大字卖点+模特图+长图详情；偏富信息。",
    },
    # ======================= 东南亚 ======================= #
    {
        "id": "shopee",
        "name": "Shopee",
        "region": "东南亚",
        "language": "en",
        "size": "1024×1024",
        "aspect": "1024x1024",
        "textDensity": "balanced",
        "templates": [
            "white_background",
            "benefit_banner",
            "lifestyle_scene",
            "multi_angle",
            "how_to_use",
        ],
        "note": "干净白底主图 1:1、≥500px，卖点图突出促销；均衡文字。",
    },
    {
        "id": "lazada",
        "name": "Lazada",
        "region": "东南亚",
        "language": "en",
        "size": "1000×1000",
        "aspect": "1024x1024",
        "textDensity": "balanced",
        "templates": [
            "white_background",
            "feature_infographic",
            "lifestyle_scene",
            "dimension_infographic",
            "detail_closeup",
        ],
        "note": "主图白底、1:1、建议 1000px 以上；均衡文字。",
    },
    {
        "id": "tokopedia",
        "name": "Tokopedia",
        "region": "东南亚 · 印尼",
        "language": "id",
        "size": "1200×1200",
        "aspect": "1024x1024",
        "textDensity": "balanced",
        "templates": [
            "white_background",
            "lifestyle_scene",
            "feature_infographic",
            "multi_angle",
            "benefit_banner",
        ],
        "note": "方图 1:1、300–1200px，主图干净白/浅底；均衡文字。",
    },
    {
        "id": "tiki",
        "name": "Tiki",
        "region": "东南亚 · 越南",
        "language": "vi",
        "size": "1200×1200",
        "aspect": "1024x1024",
        "textDensity": "balanced",
        "templates": [
            "white_background",
            "feature_infographic",
            "lifestyle_scene",
            "param_table",
            "detail_closeup",
        ],
        "note": "主图白底 1:1，正品导向，重视参数与细节；均衡文字。",
    },
    # ========================= 印度 ========================= #
    {
        "id": "flipkart",
        "name": "Flipkart",
        "region": "印度",
        "language": "en",
        "size": "2000×2000",
        "aspect": "1024x1024",
        "textDensity": "clean",
        "templates": [
            "white_background",
            "multi_angle",
            "feature_infographic",
            "lifestyle_scene",
            "detail_closeup",
        ],
        "note": "主图纯白底、无文字/水印/logo，长边≥500px(建议2000px可缩放)；偏干净少字。",
    },
    {
        "id": "meesho",
        "name": "Meesho",
        "region": "印度",
        "language": "en",
        "size": "1000×1000",
        "aspect": "1024x1024",
        "textDensity": "balanced",
        "templates": [
            "white_background",
            "model_shot",
            "benefit_banner",
            "multi_angle",
            "detail_closeup",
        ],
        "note": "主图白/浅底，服饰模特图常见，价格敏感促销风；均衡文字。",
    },
    # ========================= 欧洲 ========================= #
    {
        "id": "zalando",
        "name": "Zalando",
        "region": "欧洲 · 服饰",
        "language": "de",
        "size": "1500×2000",
        "aspect": "1024x1536",
        "textDensity": "clean",
        "templates": [
            "model_shot",
            "white_background",
            "multi_angle",
            "detail_closeup",
            "material_texture",
        ],
        "note": "时尚平台：竖版 3:4、模特实拍或幽灵人像(ghost mannequin)、纯白/浅灰底、无文字，高≥1500px。",
    },
    {
        "id": "otto",
        "name": "OTTO",
        "region": "欧洲 · 德国",
        "language": "de",
        "size": "1500×1500",
        "aspect": "1024x1024",
        "textDensity": "clean",
        "templates": [
            "white_background",
            "model_shot",
            "lifestyle_scene",
            "detail_closeup",
            "multi_angle",
        ],
        "note": "主图纯白底无文字，家居/服饰生活场景为辅；偏干净少字。",
    },
    {
        "id": "allegro",
        "name": "Allegro",
        "region": "欧洲 · 波兰",
        "language": "pl",
        "size": "1200×1200",
        "aspect": "1024x1024",
        "textDensity": "balanced",
        "templates": [
            "white_background",
            "feature_infographic",
            "multi_angle",
            "param_table",
            "detail_closeup",
        ],
        "note": "主图白底 1:1、≥1200px、无促销文字/水印；辅图可带参数，均衡。",
    },
    {
        "id": "cdiscount",
        "name": "Cdiscount",
        "region": "欧洲 · 法国",
        "language": "fr",
        "size": "1200×1200",
        "aspect": "1024x1024",
        "textDensity": "balanced",
        "templates": [
            "white_background",
            "feature_infographic",
            "lifestyle_scene",
            "param_table",
            "detail_closeup",
        ],
        "note": "主图白底、建议 1200px 起；辅图带参数/场景，均衡文字。",
    },
    {
        "id": "bol",
        "name": "Bol.com",
        "region": "欧洲 · 荷比",
        "language": "nl",
        "size": "1200×1200",
        "aspect": "1024x1024",
        "textDensity": "balanced",
        "templates": [
            "white_background",
            "feature_infographic",
            "lifestyle_scene",
            "dimension_infographic",
            "detail_closeup",
        ],
        "note": "主图纯白底无文字、≥1000px；辅图可带信息，均衡。",
    },
    {
        "id": "amazon_eu",
        "name": "Amazon 欧洲",
        "region": "欧洲",
        "language": "de",
        "size": "2000×2000",
        "aspect": "1024x1024",
        "textDensity": "clean",
        "templates": [
            "white_background",
            "feature_infographic",
            "lifestyle_scene",
            "dimension_infographic",
            "comparison",
        ],
        "note": "同 Amazon 全球规则：主图纯白底无文字、长边≥1600px；默认德语，可切换法/意/西语。",
    },
    # ==================== 中东 · 非洲 ==================== #
    {
        "id": "noon",
        "name": "noon",
        "region": "中东",
        "language": "ar",
        "size": "1000×1000",
        "aspect": "1024x1024",
        "textDensity": "balanced",
        "templates": [
            "white_background",
            "feature_infographic",
            "lifestyle_scene",
            "param_table",
            "detail_closeup",
        ],
        "note": "主图纯白底无水印、≥1000px；阿拉伯语文案从右到左，辅图可带信息，均衡。",
    },
    {
        "id": "amazon_ae",
        "name": "Amazon 中东",
        "region": "中东",
        "language": "ar",
        "size": "2000×2000",
        "aspect": "1024x1024",
        "textDensity": "clean",
        "templates": [
            "white_background",
            "feature_infographic",
            "lifestyle_scene",
            "dimension_infographic",
            "in_use_scene",
        ],
        "note": "同 Amazon 规则，主图纯白底无文字；阿拉伯语为主，偏干净少字。",
    },
    {
        "id": "jumia",
        "name": "Jumia",
        "region": "非洲",
        "language": "en",
        "size": "1000×1000",
        "aspect": "1024x1024",
        "textDensity": "balanced",
        "templates": [
            "white_background",
            "benefit_banner",
            "feature_infographic",
            "multi_angle",
            "detail_closeup",
        ],
        "note": "主图白底、≥500px(建议1000px)、无水印；促销卖点常见，均衡文字。",
    },
    # ==================== 拉丁美洲 ==================== #
    {
        "id": "mercadolibre",
        "name": "Mercado Libre",
        "region": "拉美",
        "language": "es",
        "size": "1200×1200",
        "aspect": "1024x1024",
        "textDensity": "clean",
        "templates": [
            "white_background",
            "multi_angle",
            "lifestyle_scene",
            "feature_infographic",
            "detail_closeup",
        ],
        "note": "主图纯白底、无 logo/文字/水印、产品占比≥85%、≥1200px；偏干净少字。",
    },
    {
        "id": "amazon_br",
        "name": "Amazon 巴西",
        "region": "拉美",
        "language": "pt",
        "size": "2000×2000",
        "aspect": "1024x1024",
        "textDensity": "clean",
        "templates": [
            "white_background",
            "feature_infographic",
            "lifestyle_scene",
            "dimension_infographic",
            "comparison",
        ],
        "note": "同 Amazon 规则，主图纯白底无文字；葡萄牙语为主，偏干净少字。",
    },
    # ================= 俄罗斯 · 东欧 ================= #
    {
        "id": "wildberries",
        "name": "Wildberries",
        "region": "俄罗斯",
        "language": "ru",
        "size": "900×1200",
        "aspect": "1024x1536",
        "textDensity": "rich",
        "templates": [
            "benefit_banner",
            "white_background",
            "feature_infographic",
            "param_table",
            "model_shot",
            "guarantee",
        ],
        "note": "竖版 3:4(900×1200)、俄式富信息图卡(大字卖点+参数)很常见；偏富信息。",
    },
    {
        "id": "ozon",
        "name": "Ozon",
        "region": "俄罗斯",
        "language": "ru",
        "size": "1000×1500",
        "aspect": "1024x1536",
        "textDensity": "rich",
        "templates": [
            "benefit_banner",
            "white_background",
            "feature_infographic",
            "param_table",
            "how_to_use",
            "detail_closeup",
        ],
        "note": "竖版 2:3、支持富信息图卡(rich-content)，参数/卖点齐全；偏富信息。",
    },
    # ==================== 土耳其 ==================== #
    {
        "id": "trendyol",
        "name": "Trendyol",
        "region": "土耳其",
        "language": "tr",
        "size": "1200×1800",
        "aspect": "1024x1536",
        "textDensity": "balanced",
        "templates": [
            "model_shot",
            "white_background",
            "multi_angle",
            "detail_closeup",
            "feature_infographic",
        ],
        "note": "服饰为主：竖版 2:3(1200×1800)、模特实拍、白/浅底主图；均衡文字。",
    },
    {
        "id": "hepsiburada",
        "name": "Hepsiburada",
        "region": "土耳其",
        "language": "tr",
        "size": "1500×1500",
        "aspect": "1024x1024",
        "textDensity": "balanced",
        "templates": [
            "white_background",
            "feature_infographic",
            "param_table",
            "multi_angle",
            "detail_closeup",
        ],
        "note": "主图白底 1:1、≥1500px；重视参数与多角度，均衡文字。",
    },
    # ================= 澳洲 ================= #
    {
        "id": "amazon_au",
        "name": "Amazon 澳洲",
        "region": "澳洲",
        "language": "en",
        "size": "2000×2000",
        "aspect": "1024x1024",
        "textDensity": "clean",
        "templates": [
            "white_background",
            "feature_infographic",
            "lifestyle_scene",
            "dimension_infographic",
            "outdoor_scene",
        ],
        "note": "同 Amazon 规则，主图纯白底无文字；偏干净少字，户外/生活场景常见。",
    },
    # =============== 独立站 · 社交电商 =============== #
    {
        "id": "shopify",
        "name": "Shopify",
        "region": "独立站",
        "language": "en",
        "size": "2048×2048",
        "aspect": "1024x1024",
        "textDensity": "balanced",
        "templates": [
            "transparent_cutout",
            "lifestyle_scene",
            "detail_closeup",
            "feature_infographic",
            "brand_story",
            "packaging",
        ],
        "note": "自有品牌站，风格自由，建议 2048px 方图；均衡文字。",
    },
    {
        "id": "tiktok",
        "name": "TikTok Shop",
        "region": "社交电商 · 全球",
        "language": "en",
        "size": "1080×1080 / 9:16",
        "aspect": "1024x1024",
        "textDensity": "balanced",
        "templates": [
            "vertical_lifestyle",
            "white_background",
            "benefit_banner",
            "how_to_use",
            "closeup_model",
        ],
        "note": "鼓励竖版短视频风格与模特实拍；均衡文字。",
    },
    {
        "id": "etsy",
        "name": "Etsy",
        "region": "手作 · 全球",
        "language": "en",
        "size": "2700×2025",
        "aspect": "1024x1024",
        "textDensity": "balanced",
        "templates": [
            "lifestyle_scene",
            "white_background",
            "detail_closeup",
            "size_reference",
            "brand_story",
            "packaging",
        ],
        "note": "首图偏爱生活化场景，横版 4:3，讲究品牌故事；均衡文字。",
    },
    {
        "id": "instagram",
        "name": "Instagram / FB Shop",
        "region": "社交电商",
        "language": "en",
        "size": "1080×1080 / 4:5",
        "aspect": "1024x1024",
        "textDensity": "balanced",
        "templates": [
            "lifestyle_scene",
            "flat_lay",
            "closeup_model",
            "scene_selling",
            "brand_story",
        ],
        "note": "社交信息流：方图/4:5、精致生活方式、品牌调性，文字克制；均衡。",
    },
    # ================= 通用 ================= #
    {
        "id": "custom",
        "name": "自定义",
        "region": "通用",
        "language": "zh",
        "size": "自选",
        "aspect": "1024x1024",
        "textDensity": "balanced",
        "templates": [
            "white_background",
            "feature_infographic",
            "lifestyle_scene",
            "detail_closeup",
            "model_shot",
        ],
        "note": "自由选择任意套图类型、语言与信息密度。",
    },
]

PLATFORM_BY_ID: Dict[str, Dict[str, Any]] = {p["id"]: p for p in PLATFORMS}

# Human-readable language names used in the LLM instruction.
LANGUAGE_NAMES: Dict[str, str] = {
    "en": "English",
    "zh": "Simplified Chinese (简体中文)",
    "ja": "Japanese (日本語)",
    "ko": "Korean (한국어)",
    "es": "Spanish (Español)",
    "fr": "French (Français)",
    "de": "German (Deutsch)",
    "pt": "Portuguese (Português)",
    "th": "Thai (ไทย)",
    "id": "Indonesian (Bahasa Indonesia)",
    "vi": "Vietnamese (Tiếng Việt)",
    "ar": "Arabic (العربية)",
    "pl": "Polish (Polski)",
    "nl": "Dutch (Nederlands)",
    "it": "Italian (Italiano)",
    "ru": "Russian (Русский)",
    "tr": "Turkish (Türkçe)",
    "hi": "Hindi (हिन्दी)",
}

# Platform text-density presets: label shown in the UI + instruction fed to the
# LLM describing how much on-image text to render overall.
DENSITY_NAMES: Dict[str, str] = {
    "clean": "简洁少字",
    "balanced": "均衡",
    "rich": "富信息",
}

DENSITY_INSTRUCTIONS: Dict[str, str] = {
    "clean": (
        "Overall text density: CLEAN. Keep on-image text to an absolute minimum "
        "even on info templates - short labels only, lots of whitespace, no "
        "paragraphs."
    ),
    "balanced": (
        "Overall text density: BALANCED. Use a moderate, tasteful amount of "
        "on-image text where the template calls for it."
    ),
    "rich": (
        "Overall text density: RICH. This is a text-heavy marketplace style "
        "(淘宝/天猫/京东/拼多多) - info templates should carry generous, well-organised "
        "on-image copy: multiple selling-point callouts, spec labels and short "
        "descriptive lines, while still looking clean and legible."
    ),
}
